[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "shopify.admin"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Shopify", "E-Commerce", "Admin", "Vendor/Shopify", "Area/E-Commerce", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-shopify.admin"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
